version: '3'
services:
  api:
    build: api
    ports:
      - "8000:8000"
    volumes:
      # This doesn't quite work because the app has to be installed
      # Maybe we should drop the volume mount and rely on rebuilding?
      - ./api:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8002
      - APP_URL=https://127.0.0.1:8002
      - APP_SETTINGS=/app/settings.py
      - ENV=localdev
      - DATABASE_URL=postgres://treestatususer:treestatuspassword@db/treestatusdb
      - TASKCLUSTER_SECRET=$TASKCLUSTER_SECRET
      - TASKCLUSTER_CLIENT_ID=$TASKCLUSTER_CLIENT_ID
      - TASKCLUSTER_ACCESS_TOKEN=$TASKCLUSTER_ACCESS_TOKEN
    depends_on:
      - db

  db:
    image: postgres:11
    volumes:
      - dbstore:/var/lib/postgresql/data
    ports:
      - "8102:5432"
    environment:
      - POSTGRES_USER=treestatususer
      - POSTGRES_PASSWORD=treestatuspassword
      - POSTGRES_DB=treestatusdb
    healthcheck:
      test: ["CMD-SHELL", "-c", "pg_isready -U treestatususer -d treestatusdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbstore:
